---
- hosts: all
  connection: ssh
  remote_user: "{{ docker_user }}"
  roles:
      - { role: common_setup, sudo: yes }
      - { role: docker, sudo: yes }
      - { role: docker_tls_setup, sudo: yes }
