---
# tasks file for webserver
- name: Create nginx config folder if absent
  file: path=/etc/nginx/default.d state=directory

- name: Copy frontpage config for nginx
  copy: src=12-frontpage.conf dest=/etc/nginx/default.d/
  notify:
      - start frontpage proxy
